name: Actions Workflow

on: 
  #push:
   # branches:
      #- master
     # - 'feature/*' # matches feature/* aber nicht feature/sfasf/a - dieses wird über 'feature/** gematched'
     # - 'feature/**'
    #  - '!feature/featC' # muss als letztes stehen und ignoriert den Branch featC
    #tags:
   #   - v1.*
    #paths:
  #    - '**.js' # alle JavaScript-Files im Workspace
  # repository_dispatch: 
    # types: [build]
   # schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env}}
      - name: List files
        run:  | 
          pwd
          echo "Variablen:"
          echo "SHA:" 
          echo $GITHUB_SHA
          echo "Repo:"
          echo $GITHUB_REPOSITORY
          echo "Workspace:"
          echo $GITHUB_WORKSPACE
          echo "Token"
          echo "${{ github.token }}"        
          #git clone git@github:$github:$GITHUB_REPOSITORY
          #git checkout
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        run:  | 
          pwd
          ls -al          
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
