name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container: #alle weiteren steps laufen nun nicht auf dem Runner (Host mit Ubuntu, sondern im Container ab)
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v 
      - name: Step with docker-steps with uses
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node version aus docker container with uses
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: '-v'   
      - uses: actions/checkout@v1   # chmod +x script.sh bevor commit
     # - name: Run a script
    #  uses: docker://node:12.14.1-alpine3.10
    #    with:
    #      entrypoint: ./script.sh
     #     args: "Some String"   
      #- name: send a slack messsage
       #  uses: dockr://technosophos/slack-notify
       # env:
       #   SLACK_WEBHOOK: ${{ secret....}} 
       #   SLACK_MESSAGE: "Hello slack"  
  node-docker: 
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Step1
        run: uname -a