name: "Push commit"

on: push

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Create report file
        run: date +$s > report.txt
      - name: Commit report
        run: |
          git config --global user.name "Testeruser"
          git config --global user.email "testeruser@keineahnung.de"
          git add -A
          git commit -am "Automated report"
          git push

    


