name: Context testing
on: 
  push:
  pull_request_review:

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run:  |
          echo ${{ contains( 'hello', 'll') }}
          echo ${{ startsWith( 'hello', 'he') }}
          echo ${{ endsWith( 'hello', 'lo') }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!') }}
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    # bei if muss Condition nicht in {{ }} da GitHub Actions alles inside von if als Expression bzw. Condition behandelt
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: eccho '${{ toJSON(github) }}'
      - name: Dump job context
        if: failure() # wird ausgefuehrt, wenn der step vorher nicht erfolgreich war eecho => falsch geschrieben
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always () # => wird immer ausgeführt egal was im Workflow passiert
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'